// ThriftTest.thrift
// Thrift IDL file generated by Andl -- do not edit

namespace * ThriftTest

typedef string text
typedef double number
typedef i64 time

struct ut2 {
  1: number AN;
  2: text AS;
}
struct ut3 {
  1: number AN;
  2: text AS;
  3: ut2 AU;
}
struct ut4 {
  1: bool AB;
  2: time AD;
  3: number AN;
  4: text AS;
}
struct VR4 {
  1: bool AB;
  2: time AD;
  3: number AN;
  4: text AS;
}
struct VT2 {
  1: number AN;
  2: ut2 AU;
}
struct VT4 {
  1: bool AB;
  2: time AD;
  3: number AI;
  4: text AS;
}
struct VT5 {
  1: bool AB;
  2: time AD;
  3: number AI;
  4: number AN;
  5: text AS;
}
service ThriftTestService {
  void AddVR2(
    1: list<VT2> r;
  );
  void AddVR4(
    1: list<VR4> r;
  );
  void AddVR5(
    1: list<VT5> r;
  );
  number DoErrorA(
  );
  void DoErrorB(
  );
  bool GetFB(
    1: bool v;
  );
  text GetFConcat(
    1: bool v1;
    2: time v2;
    3: number v3;
    4: number v4;
    5: text v5;
  );
  time GetFD(
    1: time v;
  );
  number GetFI(
    1: number v;
  );
  number GetFN(
    1: number v;
  );
  list<VT2> GetFR2(
    1: list<VT2> v;
  );
  list<VR4> GetFR4(
    1: list<VR4> v;
  );
  list<VT5> GetFR5(
    1: list<VT5> v;
  );
  text GetFS(
    1: text v;
  );
  VT2 GetFT2(
    1: VT2 v;
  );
  VT4 GetFT4(
    1: VT4 v;
  );
  VT5 GetFT5(
    1: VT5 v;
  );
  ut4 GetFU(
    1: ut4 v;
  );
  ut3 GetFUU(
    1: ut3 v;
  );
  bool GetVB(
  );
  text GetVConcat(
  );
  time GetVD(
  );
  number GetVI(
  );
  number GetVN(
  );
  list<VT2> GetVR2(
  );
  list<VR4> GetVR4(
  );
  list<VT5> GetVR5(
  );
  text GetVS(
  );
  VT2 GetVT2(
  );
  VT4 GetVT4(
  );
  VT5 GetVT5(
  );
  ut4 GetVU(
  );
  ut3 GetVUU(
  );
}
