// ThriftSupplierPart.thrift
// Thrift IDL file generated by Andl -- do not edit

namespace * ThriftSupplierPart

typedef string text
typedef double number
typedef i64 time

struct Part {
  1: text Pid;
  2: text PNAME;
  3: text COLOR;
  4: number WEIGHT;
  5: text CITY;
}
struct Supplier {
  1: text Sid;
  2: text SNAME;
  3: number STATUS;
  4: text CITY;
}
struct Supplies {
  1: text Sid;
  2: text Pid;
  3: number QTY;
}
struct Tquery {
  1: text Key;
  2: text Value;
}
service ThriftSupplierPartService {
  void create_supplier(
    1: list<Supplier> s;
  );
  void delete_supplier(
    1: text sid;
  );
  list<Supplier> find_supplier(
    1: text sid;
  );
  list<Part> findall_part(
  );
  list<Supplier> findall_supplier(
  );
  list<Supplies> findall_supplies(
  );
  list<Part> findsome_part(
    1: list<Tquery> query;
  );
  void update_supplier(
    1: text sid;
    2: list<Supplier> s;
  );
}
